### ISSUE TITLE
Arduino Code Header

### ISSUE THREAD

**Issue by jonashae** [muthesius/pepe#16]
ImHeader sollte die Pepe-Version, eine "Generated by", etc stehen

**Comment by jonashae** [comment]
/*!
    pepe 
    VVVV to Arduino Composer
    jonas, jens a. ewald
    generated at ID Lab muthesiusKH 
    version: 0.0.1 - 2015
    https://github.com/muthesius/pepe 
*/

**Comment by jnslxndr** [comment]
oder auch:

```
/* THIS FILE WAS GENERATED BY **
  pepe – An VVVV Arduino Code Generator
  version: 0.0.1
  jonas häutle
  Muthesius Academy of Fine Arts & Design, 2014-15
  License MIT
  https://github.com/muthesius/pepe
*/
```

**Comment by jonashae** [comment]
finde ich gut aber jonas als name sollte reichen... und ich hätte wohl ein besseres gefühl wenn das interface labor / muthesius genannt werden würde und nicht die Muthesius Hochschule als gesamte bzw. einzelne Institution:

/\* THIS FILE WAS GENERATED BY **
  vage– An VVVV Arduino Code Generator
  version: 0.0.1
  jonas 
  Interface Laboratory 
  Muthesius Academy of Fine Arts & Design, 2014-15
  License MIT
  https://github.com/muthesius/pepe
*/

**Comment by jnslxndr** [comment]
`vage`? haben wir da noch einen neuen name :smile: 
von meiner seite aus ok mit deinem namen. ein _interface laboratory_ gibt es (leider) nicht, dann eher _Interfacedesign_ oder _Prototyping Studio_

**Comment by jonashae** [comment]
```
/* THIS FILE WAS GENERATED BY **
pepe– An VVVV Arduino Code Generator
version: 0.0.1
jonas 
Prototyping Studio - Interface Design
Muthesius Academy of Fine Arts & Design, 2014-15
License MIT
https://github.com/muthesius/pepe
*/
```

**Comment by jnslxndr** [comment]
jep, kann man so wohl für alles verwenden :)
kleine notiz: zwischen `pepe` und `–` muss noch ein leerzeichen!
