### ISSUE TITLE
Arbeiten mit Git

### ISSUE THREAD

**Issue by jonashae** [muthesius/pepe#2]
Moin,
wie genau arbeitet bzw. soll man in github normale (wie diese) Diskussionen führen - hätte ein paar allgemeine Fragen zum Konzept und irgendwie passt das nicht in den Quellcode - wenn ich für jede Frage ein Issus anlege ist das irgendwie unübersichtlich - und ein Issue als Diskussionsplattform zu verwenden ist irgendwie auch komisch?... Mails wären wiederum geschlossen etc. - keine Ahnung hab noch nicht in Github gearbeitet und kenn die Konventionen nicht ;-)

**Comment by jnslxndr** [comment]
:) siehe #1 meine antwort wäre allerdings hier (#2) besser gewesen :(
man kann sich auch einen milestone anlegen und dann die issues entsprechend zuordnen...
