### ISSUE TITLE
Projekt Name

### ISSUE THREAD

**Issue by jonashae** [muthesius/pepe#7]
VAVA vs. PEPE

**Comment by jnslxndr** [comment]
sollte sich hier noch ein anderer name ergeben, bitte daran denke den code header (#16) noch entsprechend anzupassen!

**Comment by jnslxndr** [comment]
btw. :) **AVAV** geht auch:

**A** **V**VVV **A**rduino **V**riter

**Comment by jonashae** [comment]
habs auf pepe gesetzt ist leichter zu schreiben ;-) zumindest mit 10 finger System ha interface design ...
